apiVersion: v1
kind: Service
metadata:
  name: tdi-package-ui2
  namespace: ontour-dev
spec:
  selector:
    app: tdi-package-ui2
  ports:
  - port: 8081
    targetPort: 80
  type: ClusterIP
status:
  loadBalancer: {}
